<?use DYP\Tags\Element;?>
<?$title = "Software Manager Service / Package Management" ?>

<?=$this->tag->javascriptInclude("assets/js/layer/layer.js");?>

<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small><?=$title?></small>
        </div>
    </div>

    <div class="am-g am-margin-bottom-xs">

        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs  am-align-right">
                    <button type="button" class="am-btn am-btn-secondary am-round" data-am-modal="{target: '#newRecord'}"><span class="am-icon-plus"></span> New</button>
                </div>
                <button type="button" id="release" class="am-btn am-btn-xs am-btn-success am-round"><span class="am-icon-cloud-upload"></span> Release</button>
                <button type="button" id="reloadPage" style="display: none;" onclick="window.location.reload()" class="am-btn am-btn-xs am-btn-warning am-round"><span class="am-icon-retweet"></span> Reload</button>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-6 am-text-right">
            <a href="<?=$_SERVER['REQUEST_SCHEME']?>://<?=$_SERVER['SERVER_NAME']?>/api/swmgr?type=category" target="_blank"
               class="am-badge am-round am-badge-secondary am-text-xs">
                Test API
            </a>

            <span class="am-badge am-round am-badge-secondary am-text-xs">PAGES: <strong><?=$page->total_pages?></strong></span>
            <span class="am-badge am-round am-badge-primary am-text-xs">RECORDS: <strong><?=$page->total_items?></strong></span>
            <span class="am-badge am-round am-badge-danger am-text-xs">VERSION: <strong><?=date("Y-m-d H:i:s", $svc->vcode)?></strong></span>

        </div>

    </div>


    <div class="am-g">
        <div class="am-u-sm-12">


            <table class="am-table am-table-bordered am-table-radius am-table-striped">
                <? foreach($page->items as $key => $p): ?>
                    <tr>
                        <td><img src="<?=$p->iconUrl?>" width="48" alt=""></td>
                        <td>
                            <?=$p->name?>&nbsp;<span class="am-badge am-badge-secondary"><?=($p->arch==96)?'32/64':$p->arch?></span>
                            <br>
                            <small>SIZE:<?=DYP\Sys\Command::fmtDataSize($p->size)?>, &nbsp;VER:<?=$p->versionName?></small>
                        </td>
                        <td><?=$p->brief?>&nbsp;<a href="javascript:$('#updateinfo_<?=$p->id?>').toggle()">更新信息&nbsp;<span class="am-icon-angle-double-down"></span></a>
                            <div style="display: none;" class="am-text-primary" id="updateinfo_<?=$p->id?>"><?=nl2br(htmlspecialchars($p->updateInfo))?></div>
                        </td>
                        <td>
                            <?if(!empty($p->downloadUrl)):?>
                                <span id="download_id_<?=$p->id?>">
                                    <script>fileExists("download_id_<?=$p->id?>", "<?=$p->downloadUrl?>",
                                            '<a href="<?=$p->downloadUrl?>" target="_blank" class="am-btn am-btn-xs am-btn-danger">404 | 找不到了</a>',
                                            '<a href="<?=$p->downloadUrl?>" target="_blank" class="am-btn am-btn-xs am-btn-warning">503 | 下载不到</a>',
                                            '<a href="<?=$p->downloadUrl?>" target="_blank" class="am-btn am-btn-xs am-btn-secondary">200 | 正常下载</a>'
                                        );
                                    </script></span>
                            <?else:?>
                                <button class="am-btn am-btn-xs am-btn-danger">NO SET</button>
                            <?endif?>
                        </td>
                    </tr>
                <?endforeach?>
            </table>


            <ul class="am-pagination am-pagination-right">
                <li><?=$this->tag->linkTo('cp/swmgr', '<span class="am-icon-angle-double-left"></span>')?></li>
                <li><?=$this->tag->linkTo("cp/swmgr?page=" . $page->before, '<span class="am-icon-angle-left"></span>')?></li>
                <li class="am-active"><?=$this->tag->linkTo("#", $page->current)?></li>
                <li><?=$this->tag->linkTo("cp/swmgr?page=" . $page->next, '<span class="am-icon-angle-right"></span>')?></li>
                <li><?=$this->tag->linkTo("cp/swmgr?page=" . $page->last, '<span class="am-icon-angle-double-right"></span>')?></li>
                <li><span class="help-inline"><?=$page->current?> of <?=$page->total_pages?></span></li>
            </ul>

        </div>

    </div>
</div>
<!-- content end -->


<script>
    $(function(){
        $("[data-rel='detect']").bind('click', function(){

            var fUrl = $.trim($(this).attr('data-var'));

            if (fUrl !== '') {
                $(this).button('Checking...');
                $.getJSON('/cp/rfexists?file='+fUrl, function(resp){
                    $(this).button('reset');
                    console.log(resp);
                });
            }

        });

        /**
         * Release task
         */
        $("#release").click(function(){
            /*
             layer.confirm('Are you sure?', {icon: 3}, function(index){
             layer.close(index);
             $("#release span").removeClass("am-icon-cloud-upload").addClass("am-icon-spinner am-icon-pulse");

             $.ajax({
             url: '<?=$_SERVER['REQUEST_URI']?>',
             type: 'PUT',
             //async:false,
             cache:false,
             success: function(response) {
             $("#release span").removeClass("am-icon-spinner am-icon-pulse").addClass("am-icon-cloud-upload");
             if(response.code == 0) {
             $("#release").attr("disabled", true).hide();
             $("#reloadPage").show();
             layer.msg(response.msg);
             layer.tips('Upload Successfully, Please Refresh This Page!', '#reloadPage',{tips: [1, '#f37b1d'],time: 400000});
             }else{
             layer.alert(response.msg, {icon: 11});
             }
             }
             }, 'JSON');
             });
             */
        });//end

    });

</script>
