<? $title = "意见反馈" ?>

<!-- content start -->
<div class="am-g" style="margin:0;padding:0;width: 100%">

        <div class="am-panel am-panel-default">
            <div class="am-panel-hd">
                <h3 class="am-panel-title am-text-center">感谢您的支持,有你的支持我们才能做的更好!<a href="javascript:window.close()" class="am-align-right am-close am-close-alt am-icon-times"></a></h3>
            </div>
            <div class="am-panel-bd">

                <form class="am-form am-form-horizontal">

                    <div class="am-form-group">
                        <label for="doc-ipt-3" class="am-u-sm-2 am-form-label">QQ</label>
                        <div class="am-u-sm-10">
                            <input type="email" id="doc-ipt-3" placeholder="请输入你的QQ号码,以便联系">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="doc-ipt-3" class="am-u-sm-2 am-form-label">电子邮件</label>
                        <div class="am-u-sm-10">
                            <input type="email" id="doc-ipt-3" placeholder="请输入你的电子邮件,以便联系">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="doc-ipt-3" class="am-u-sm-2 am-form-label">手机</label>
                        <div class="am-u-sm-10">
                            <input type="email" id="doc-ipt-3" placeholder="请输入你的手机号码,以便联系">
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="doc-ipt-pwd-2" class="am-u-sm-2 am-form-label">反馈类型</label>
                        <div class="am-u-sm-10">
                            <label for="problemType_1"><input name="problemType" id="problemType_1" type="radio"> 问题反馈</label>
                            <label for="problemType_2"><input name="problemType" id="problemType_2" type="radio"> 功能建议</label>
                            <label for="problemType_3"><input name="problemType" id="problemType_3" type="radio"> 举报可疑网站</label>
                            <label for="problemType_4"><input name="problemType" id="problemType_4" type="radio"> 举报病毒</label>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <label for="doc-ipt-pwd-2" class="am-u-sm-2 am-form-label">反馈内容</label>
                        <div class="am-u-sm-10">
                            <textarea class="am-u-sm-8" rows="5" id="doc-ta-1"></textarea>
                        </div>
                    </div>

                    <div class="am-form-group">
                        <div class="am-u-sm-10 am-u-sm-offset-2">
                            <button type="submit" class="am-btn am-btn-secondary">提 交</button>
                        </div>
                    </div>
                </form>


            </div>
        </div>

    </div>
</div>
<!-- content end -->
