<? $title = "意见反馈" ?>

<!-- content start -->
<div class="am-g">
    <div class="am-u-sm-12">



        <div class="am-tabs" data-am-tabs="{noSwipe: 1}" id="doc-tab-demo-1">
            <ul class="am-tabs-nav am-nav am-nav-tabs">
                <li class="am-active"><a href="javascript: void(0)">问题反馈</a></li>
                <li><a href="javascript: void(0)">功能建议</a></li>
                <li><a href="javascript: void(0)">举报可疑网站</a></li>
                <li><a href="javascript: void(0)">举报病毒</a></li>
            </ul>

            <div class="am-tabs-bd">

                <!--问题反馈-->
                <div class="am-tab-panel am-active">

                    <form action="" method="get">
                        <div class="tab-pane fade in active mshe" id="Feedback">
                            <div class="form-group">
                                <label for="name">问题名称</label>
                                <input type="text" class="form-control" id="name" placeholder="填写反馈名称">
                            </div>
                            <div class="form-group">
                                <label for="name" style="float:left;">反馈内容</label>
                                <textarea class="form-control" rows="3"></textarea>
                            </div>
                            <button type="submit" data-loading-text="Loading..." class="btn btn-primary" autocomplete="off">提交</button>
                    </form>

                </div><!--问题反馈-->

                <!--功能建议-->
                <div class="am-tab-panel">

                    <form action="" method="get">
                        <div class="form-group">
                            <label for="name">建议名称</label>
                            <input type="text" class="form-control" id="name" placeholder="填写建议名称">
                        </div>
                        <div class="form-group">
                            <label for="name" style="float:left;">建议内容</label>
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" data-loading-text="Loading..." class="btn btn-primary" autocomplete="off">提交</button>
                    </form>

                </div><!--功能建议-->

                <!--举报可疑网站-->
                <div class="am-tab-panel">

                    <form action="" method="get">
                        <div class="form-group">
                            <label for="name">举报可疑网站</label>
                            <input type="text" class="form-control" id="name" placeholder="请输入网址">
                        </div>
                        <div class="form-group">
                            <label for="name" style="float:left;">反馈建议</label>
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" data-loading-text="Loading..." class="btn btn-primary" autocomplete="off">提交</button>
                    </form>

                </div><!--举报可疑网站-->

                <!--举报病毒-->
                <div class="am-tab-panel">

                    <form action="" method="get">
                        <div class="form-group">
                            <label for="name">举报名称</label>
                            <input type="text" class="form-control" id="name" placeholder="请输入举报名称">
                        </div>
                        <div class="form-group">
                            <label for="name" style="float:left;">举报内容</label>
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" data-loading-text="Loading..." class="btn btn-primary" autocomplete="off">提交</button>
                    </form>

                </div><!--举报病毒-->

            </div><!--am-tabs-bd-->
        </div><!--am-tabs-->



    </div>
</div>
<!-- content end -->
