<? $title = "意见反馈" ?>

<!-- content start -->
<div class="am-g">
    <div class="am-u-sm-12">

        <div class="am-panel am-panel-default">
            <div class="am-panel-hd">
                <h3 class="am-panel-title">用户反馈<a href="javascript:window.close()" class="am-align-right am-close am-close-alt am-icon-times"></a></h3>
            </div>
            <div class="am-panel-bd">

                <form class="am-form">
                    <fieldset>
                        <legend>谢谢您的支持,让我们做的更好!</legend>

                        <div class="am-form-group">
                            <label for="doc-ipt-email-1">QQ</label>
                            <input type="email" class="" id="doc-ipt-email-1" placeholder="请输入您的QQ号码">
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-email-1">邮箱</label>
                            <input type="email" class="" id="doc-ipt-email-1" placeholder="请输入您的邮箱">
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ipt-email-1">手机号码</label>
                            <input type="email" class="" id="doc-ipt-email-1" placeholder="请输入您的手机号码">
                        </div>

                        <div class="am-checkbox">
                            <label><input type="radio"> 问题反馈</label>
                            <label><input type="radio"> 功能建议</label>
                            <label><input type="radio"> 举报可疑网站</label>
                            <label><input type="radio"> 举报病毒</label>
                        </div>

                        <div class="am-form-group">
                            <label class="am-radio-inline">
                                <input type="radio"  value="" name="docInlineRadio"> 每一分
                            </label>
                            <label class="am-radio-inline">
                                <input type="radio" name="docInlineRadio"> 每一秒
                            </label>
                            <label class="am-radio-inline">
                                <input type="radio" name="docInlineRadio"> 多好
                            </label>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-select-1">下拉多选框</label>
                            <select id="doc-select-1">
                                <option value="option1">选项一...</option>
                                <option value="option2">选项二.....</option>
                                <option value="option3">选项三........</option>
                            </select>
                            <span class="am-form-caret"></span>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-select-2">多选框</label>
                            <select multiple class="" id="doc-select-2">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                        </div>

                        <div class="am-form-group">
                            <label for="doc-ta-1">文本域</label>
                            <textarea class="" rows="5" id="doc-ta-1"></textarea>
                        </div>

                        <p><button type="submit" class="am-btn am-btn-default">提交</button></p>
                    </fieldset>
                </form>

            </div>
        </div>

    </div>
</div>
<!-- content end -->
