<?use DYP\Tags\Element;?>
<?$title = "User Manager Service / Harddisk User" ?>

<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small><?=$title?></small>
        </div>
    </div>


    <div class="am-g am-margin-bottom-xs">

        <div class="am-u-sm-12 am-u-md-12 am-text-right">
            <span class="am-badge am-round am-badge-secondary am-text-xs">PAGES: <strong><?=$page->total_pages?></strong></span>
            <span class="am-badge am-round am-badge-primary am-text-xs">RECORDS: <strong><?=$page->total_items?></strong></span>
        </div>
    </div>


    <div class="am-g">
        <div class="am-u-sm-12">


            <?/*Summary*/?>
            <div class="am-tab-panel am-fade am-in am-active" id="tab_summary">

                <table id="SummaryTable" class="am-table am-table-bordered am-table-radius am-table-compact am-table-striped am-table-hover table-main">
                    <thead>
                    <tr>
                        <? foreach($page->items[0] as $k => $v): ?>

                            <th class="am-text-center">
                                <?if(strtolower($k) == 'status'):?>
                                    STATUS
                                <?else:?>
                                    <?=strtoupper($k)?>
                                <?endif?>
                            </th>
                        <? endforeach ?>
                    </tr>
                    </thead>
                    <tbody>
                    <? foreach($page->items as $key => $p): ?>
                        <tr id="<?=$p->id?>">
                            <? foreach($p as $key => $v): ?>
                                <td class="am-text-center">
                                    <?=strtoupper($v)?>
                                </td>
                            <? endforeach ?>
                        </tr>
                    <? endforeach ?>
                    </tbody>
                </table>

                <ul class="am-pagination am-pagination-right">
                    <li><?=$this->tag->linkTo('cp/user/hduser', '<span class="am-icon-angle-double-left"></span>')?></li>
                    <li><?=$this->tag->linkTo("cp/user/hduser?page=" . $page->before, '<span class="am-icon-angle-left"></span>')?></li>
                    <li class="am-active"><?=$this->tag->linkTo("#", $page->current)?></li>
                    <li><?=$this->tag->linkTo("cp/user/hduser?page=" . $page->next, '<span class="am-icon-angle-right"></span>')?></li>
                    <li><?=$this->tag->linkTo("cp/user/hduser?page=" . $page->last, '<span class="am-icon-angle-double-right"></span>')?></li>
                    <li><span class="help-inline"><?=$page->current?> of <?=$page->total_pages?></span></li>
                </ul>

            </div>
            <?/*Summary end*/?>


        </div>

    </div>
</div>
<!-- content end -->
