<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title><?=(isset($title))?$title:""?> | 乐网</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta "Access-Control-Allow-Origin"="*">
    <meta "Access-Control-Allow-Headers"="X-Requested-With">
    <meta "Access-Control-Allow-Headers"="Content-Type">
    <link rel="stylesheet" href="/assets/am/css/amazeui.min.css"/>
    <link rel="stylesheet" href="/assets/am/css/amazeui.flat.min.css"/>
    <link rel="stylesheet" href="/assets/am/css/admin.css"/>

    <script src="/assets/am/js/jquery.min.js"></script>
    <script src="/assets/am/js/amazeui.min.js"></script>

</head>
<body style="overflow: hidden;background-color:transparent;">

<?= $this->getContent() ?>

</body>
</html>
