<? $title = "管理首页" ?>
<? //=$this->tag->stylesheetLink("assets/am/css/admin.css");?>
<? //=$this->tag->javascriptInclude("javascript/jquery.min.js");?>



<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small>Summary</small>
        </div>
    </div>

    <ul class="am-avg-sm-1 am-avg-md-5 am-margin am-padding am-text-center admin-content-list ">
        <li><a href="#" class="am-text-primary">
                <span class="am-icon-btn am-primary am-icon-group"></span><br/>用户总量<br/>
                <strong><?=number_format($userTotal)?></strong></a>
        </li>

        <li><a href="#" class="am-text-success">
                <span class="am-icon-btn am-success am-icon-user-plus"></span><br/>今日用户新增<br/>
                <strong><?=number_format($todayUserTotal)?></strong></a>
        </li>

        <li><a href="#" class="am-text-secondary">
                <span class="am-icon-btn am-secondary am-icon-user-md"></span><br/>在线用户<br/>
                <strong><?=is_numeric($OnlineUser)?number_format($OnlineUser):$OnlineUser;?></strong></a>
        </li>

        <li><a href="#" class="am-text-danger">
                <span class="am-icon-btn am-danger am-icon-area-chart"></span><br/>历史访客<br/>
                <strong><?=is_numeric($HistoryVisitors)?number_format($HistoryVisitors):$HistoryVisitors;?></strong></a>
        </li>

        <li><a href="#" class="am-text-warning">
                <span class="am-icon-btn am-warning am-icon-clock-o"></span><br/>今日独立访客<br/>
                <strong><?=is_numeric($TotalUnique)?number_format($TotalUnique):$TotalUnique;?></strong></a>
        </li>

    </ul>


    <div class="am-g">
        <div class="am-u-md-6">

            <div class="am-panel am-panel-default">
                <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-1'}">Service Statistics<span
                        class="am-icon-chevron-down am-fr"></span></div>
                <div id="collapse-panel-1" class="am-in">
                    <table class="am-table am-table-bd am-table-bdrs am-table-striped am-table-hover">
                        <tbody>

                        <tr>
                            <th class="am-text-center">#</th>
                            <th class="am-text-center">Service</th>
                            <th class="am-text-center">Request</th>
                            <th class="am-text-center">Installed</th>
                        </tr>

                        <?foreach ($svc as $item):?>
                        <tr>
                            <td class="am-text-center"><?=$item->svc->id?></td>
                            <td class="am-text-center" data-am-popover="{content: '<?=$item->svc->description?>', trigger: 'hover focus'}"><?=$item->svc->name?></td>
                            <td class="am-text-center"><?=number_format($item->ct->request)?></td>
                            <td class="am-text-center"><?=number_format($item->ct->download)?></td>
                        </tr>
                        <?endforeach?>
                        </tbody>
                    </table>
                </div>
            </div>



            <div class="am-panel am-panel-warning">
                <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-2'}">Browser Top<span
                        class="am-icon-chevron-down am-fr"></span></div>
                <div id="collapse-panel-2" class="am-in">
                    <table class="am-table am-table-bd am-table-bdrs am-table-striped am-table-hover">
                        <tbody>
                        
                        <tr>
                            <th class="am-text-center">#</th>
                            <th>BROWSER</th>
                            <th>NAME</th>
                            <th>DOWNLOADS</th>
                        </tr>
                        <? foreach ($swmgrBrowserTop as $k=>$v):?>
                            <tr>
                                <td class="am-text-center"><?=$v->baiduid?></td>
                                <td class="am-text-center"><img src="<?=$v->iconUrl?>" alt="" title="<?=$v->developer?>"></td>
                                <td><?=$v->name?>-<?=$v->versionName?>-<?=$v->versionType?></td>
                                <td><?=$v->dlcount?></td>
                            </tr>
                        <?endforeach?>

                        </tbody>
                    </table>
                </div>
            </div>



        </div>

        <div class="am-u-md-6">



            <div class="am-panel am-panel-secondary">
                <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-3'}">XB::Software Manager<span
                        class="am-icon-chevron-down am-fr"></span></div>
                <div id="collapse-panel-3" class="am-in">
                    <table class="am-table am-table-bd am-table-bdrs am-table-striped am-table-hover">
                        <tbody>
                        <tr>
                            <th class="am-text-center">#</th>
                            <th class="am-text-center">SERVICE</th>
                            <th class="am-text-center">TOTAL</th>
                            <th class="am-text-center">TODAY</th>
                        </tr>
                        <tr>
                            <td class="am-text-center">1</td>
                            <td class="am-text-center">Installation Source</td>
                            <td class="am-text-center"><?=$pkgSrcTotal?></td>
                            <td class="am-text-center">Unknown</td>
                        </tr>
                        <tr>
                            <td class="am-text-center">2</td>
                            <td class="am-text-center">Collect Package</td>
                            <td class="am-text-center"><?=$pkgClientTotal?></td>
                            <td class="am-text-center">Unknown</td>
                        </tr>
                        <tr>
                            <td class="am-text-center">3</td>
                            <td class="am-text-center">Users installed</td>
                            <td class="am-text-center"><?=$pkgUserTotal?></td>
                            <td class="am-text-center">Unknown</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>




            <div class="am-panel am-panel-success">
                <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-4'}">Software Top 10<span
                        class="am-icon-chevron-down am-fr"></span></div>
                <div id="collapse-panel-4" class="am-in">
                    <table class="am-table am-table-bd am-table-bdrs am-table-striped am-table-hover">
                        <tbody>
                        <tr>
                            <th class="am-text-center">#</th>
                            <th>ICON</th>
                            <th>NAME</th>
                            <th>DOWNLOADS</th>
                        </tr>
                        <? foreach ($swmgrSwTop as $k=>$v):?>
                            <tr>
                                <td class="am-text-center"><?=$v->baiduid?></td>
                                <td class="am-text-center"><img src="<?=$v->iconUrl?>" alt="" title="<?=$v->developer?>"></td>
                                <td><?=$v->name?>-<?=$v->versionName?>-<?=$v->versionType?></td>
                                <td><?=$v->dlcount?></td>
                            </tr>
                        <?endforeach?>
                        </tbody>
                    </table>
                </div>
            </div>


        </div>




    </div>

</div>
<!-- content end -->
