<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title><?=(isset($title))?$title:""?> | <?=_("PROJECT_TITLE_SUFFIX")?></title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="format-detection" content="telephone=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>
  <link rel="alternate icon" type="image/png" href="/assets/am/i/favicon.png">
  <link rel="stylesheet" href="/assets/am/css/amazeui.min.css"/>
  <link rel="stylesheet" href="/assets/am/css/amazeui.flat.min.css"/>

  <style>

  </style>
  <link rel="stylesheet" href="/assets/css/layout.css" />
  <link rel="stylesheet" href="/assets/css/index.css" />

</head>
<body>

<?=$this->getContent()?>

</body>
</html>
