<? $title = "帮助中心" ?>

<!-- content start -->
<div class="am-g" style="margin:0;padding:0;width: 100%">

    <div class="am-panel am-panel-default">
        <div class="am-panel-hd">
            <h3 class="am-panel-title am-text-center">帮助中心<a href="javascript:window.close()" class="am-align-right am-close am-close-alt am-icon-times"></a></h3>
        </div>
        <div class="am-panel-bd">






            <div data-am-widget="list_news" class="am-list-news am-list-news-default" >
                <!--列表标题-->
                <div class="am-list-news-hd am-cf">
                    <!--带更多链接-->
                    <a href="##" class="">
                        <h2>乐网软件管家</h2>
                        <span class="am-list-news-more am-fr">更多 &raquo;</span>
                    </a>
                </div>

                <div class="am-list-news-bd">
                    <ul class="am-list">

                        <li class="am-g am-list-item-dated">
                            <a href="##" class="am-list-item-hd ">软件管家收费吗?</a>

                            <span class="am-list-date">2013-09-18</span>


                        </li>
                        <li class="am-g am-list-item-dated">
                            <a href="##" class="am-list-item-hd ">我要的软件没找到怎么办?</a>

                            <span class="am-list-date">2013-10-14</span>


                        </li>
                        <li class="am-g am-list-item-dated">
                            <a href="##" class="am-list-item-hd ">软件管家有什么特色?</a>

                            <span class="am-list-date">2013-11-18</span>


                        </li>
                    </ul>
                </div>

            </div>




            <div data-am-widget="list_news" class="am-list-news am-list-news-default" >
                <!--列表标题-->
                <div class="am-list-news-hd am-cf">
                    <!--带更多链接-->
                    <a href="##" class="">
                        <h2>系统安装</h2>
                        <span class="am-list-news-more am-fr">更多 &raquo;</span>
                    </a>
                </div>

                <div class="am-list-news-bd">
                    <ul class="am-list">

                        <li class="am-g am-list-item-dated">
                            <a href="##" class="am-list-item-hd ">我的电脑适合安装什么样的系统?</a>

                            <span class="am-list-date">2013-09-18</span>


                        </li>
                        <li class="am-g am-list-item-dated">
                            <a href="##" class="am-list-item-hd ">我的XP为什么不能打开导航?</a>

                            <span class="am-list-date">2013-10-14</span>


                        </li>
                        <li class="am-g am-list-item-dated">
                            <a href="##" class="am-list-item-hd ">为什么小白系统不能自动激活系统?</a>

                            <span class="am-list-date">2013-11-18</span>


                        </li>
                    </ul>
                </div>

            </div>




        </div>
    </div>

</div>
</div>
<!-- content end -->
