<a class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

<footer>
  <hr>
  <p class="am-padding-left">&copy; <?=date("Y")?> Datacld.Com. Powered By Hurricane Team.</p>
</footer>

<!--[if lt IE 9]>
<script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
<script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
<script src="/assets/am/js/polyfill/rem.min.js"></script>
<script src="/assets/am/js/polyfill/respond.min.js"></script>
<script src="/assets/am/js/amazeui.legacy.js"></script>
<![endif]-->

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="/assets/am/js/jquery.min.js"></script>
<script src="/assets/am/js/amazeui.min.js"></script>
<!--<![endif]-->
<script src="/assets/am/js/app.js"></script>
</body>
</html>
