<a class="am-icon-btn am-icon-th-list am-show-sm-only admin-menu" data-am-offcanvas="{target: '#admin-offcanvas'}"></a>

<footer>
  <hr>
  <p class="am-padding-left am-text-center">
    &copy; <?=date("Y")?> Datacld.Com. Powered By Hurricane Team.
    &nbsp;&nbsp;
    <span class="am-badge am-round am-badge-<?=str_replace(array('development','testing','production'), array('danger','warning','success'), $GLOBALS['__DYRUNMODE__'])?>"><?=$GLOBALS['__DYRUNMODE__']?></span>
  </p>
</footer>

</body>
</html>
