
<!-- sidebar start -->
<div class="admin-sidebar am-offcanvas" id="admin-offcanvas">
    <div class="am-offcanvas-bar admin-offcanvas-bar">
        <ul class="am-list admin-sidebar-list">
            <li><a href="/cp"><span class="am-icon-home"></span> Home</a></li>
            <li class="admin-parent">
                <a class="am-cf" data-am-collapse="{target: '#collapse-nav'}"><span class="am-icon-cogs"></span> Service Management <span class="am-icon-angle-right am-fr am-margin-right"></span></a>
                <ul class="am-list am-collapse admin-sidebar-sub am-in" id="collapse-nav">
                    <li><a href="/cp/coresvc" class="am-cf"><span class="am-icon-cog"></span> Core services<span class="am-icon-star am-fr am-margin-right admin-icon-yellow"></span></a></li>
                    <li><a href="/cp/xbspeed"><span class="am-icon-share-alt"></span> xbSpeed service</a></li>
                    <li><a href="/cp/presoftware"><span class="am-icon-cloud-download"></span> Pre installed software</a></li>
                </ul>
            </li>
            <li><a href="/cp/analysis"><span class="am-icon-pie-chart"></span> Statistical Analysis</a></li>
            <li><a href="/cp/logout"><span class="am-icon-sign-out"></span> Security Exit</a></li>
        </ul>

        <div class="am-panel am-panel-default admin-sidebar-panel">
            <div class="am-panel-bd">
                <p><span class="am-icon-flag"></span> Wisdom</p>
                <p>The unexamined life is not worth living. -- Socrates</p>
            </div>
        </div>

        <div class="am-panel am-panel-default admin-sidebar-panel">
            <div class="am-panel-bd">
                <p><span class="am-icon-bullhorn"></span> Note</p>
                <p>Victory belongs to the most persevering.</p>
            </div>
        </div>
    </div>
</div>
<!-- sidebar end -->
