<?use DYP\Tags\Element;?>
<?$title = "Software Manager Service / Package Management" ?>
<?=$this->tag->javascriptInclude("assets/js/layer/layer.js");?>

<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small><?=$title?></small>
        </div>
    </div>

    <div class="am-g am-margin-bottom-xs">

        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs  am-align-right">
                    <button type="button" class="am-btn am-btn-secondary am-round" data-am-modal="{target: '#newRecord'}"><span class="am-icon-plus"></span> New</button>
                </div>
                <button type="button" id="release" class="am-btn am-btn-xs am-btn-success am-round"><span class="am-icon-cloud-upload"></span> Release</button>
                <button type="button" id="reloadPage" style="display: none;" onclick="window.location.reload()" class="am-btn am-btn-xs am-btn-warning am-round"><span class="am-icon-retweet"></span> Reload</button>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-6 am-text-right">
            <a href="<?=$_SERVER['REQUEST_SCHEME']?>://<?=$_SERVER['SERVER_NAME']?>/api/ctr?svc=swmgr" target="_blank"
               class="am-badge am-round am-badge-secondary am-text-xs">
                Test API
            </a>
            &nbsp;&nbsp;
            <span class="am-badge am-round am-badge-warning am-text-xs">Total: <strong><?=sizeof($task)?></strong></span>
            &nbsp;&nbsp;
            <span class="am-badge am-round am-badge-danger am-text-xs">Version: <strong><?=date("Y-m-d H:i:s", $vsvc->vcode)?></strong></span>

        </div>

    </div>


    <div class="am-g">
        <div class="am-u-sm-12">

            <div class="am-tabs-bd">
                <?/*Summary*/?>
                <div class="am-tab-panel am-fade am-in am-active" id="tab_summary">

                    <ul class="am-list am-list-static am-list-border">
                        <? foreach($task as $key => $p): ?>
                            <li>
                                <?if(!empty($p->downloadUrl)):?>
                                    <span class="am-badge am-badge-primary"><?=$p->downloadUrl?></span>
                                <?else:?>
                                    <span class="am-badge am-badge-danger">无下载地址</span>
                                <?endif?>

                                <?=$p->name?> - <?=$p->versionName?>
                            </li>
                        <?endforeach?>
                    </ul>

                </div>
                <?/*Summary end*/?>
            </div>

        </div>

    </div>
</div>
<!-- content end -->


<script>
    $(function(){
        /**
         * Release task
         */
        $("#release").click(function(){
            /*
             layer.confirm('Are you sure?', {icon: 3}, function(index){
             layer.close(index);
             $("#release span").removeClass("am-icon-cloud-upload").addClass("am-icon-spinner am-icon-pulse");

             $.ajax({
             url: '<?=$_SERVER['REQUEST_URI']?>',
             type: 'PUT',
             //async:false,
             cache:false,
             success: function(response) {
             $("#release span").removeClass("am-icon-spinner am-icon-pulse").addClass("am-icon-cloud-upload");
             if(response.code == 0) {
             $("#release").attr("disabled", true).hide();
             $("#reloadPage").show();
             layer.msg(response.msg);
             layer.tips('Upload Successfully, Please Refresh This Page!', '#reloadPage',{tips: [1, '#f37b1d'],time: 400000});
             }else{
             layer.alert(response.msg, {icon: 11});
             }
             }
             }, 'JSON');
             });
             */
        });//end

    });

</script>
