<?use DYP\Tags\Element;?>
<?$title = "Software Manager Service / Package Management" ?>
<?=$this->tag->javascriptInclude("assets/js/layer/layer.js");?>

<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small><?=$title?></small>
        </div>
    </div>

    <div class="am-g am-margin-bottom-xs">

        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs  am-align-right">
                    <button type="button" class="am-btn am-btn-secondary am-round" data-am-modal="{target: '#newRecord'}"><span class="am-icon-plus"></span> New</button>
                </div>
                <button type="button" id="release" class="am-btn am-btn-xs am-btn-success am-round"><span class="am-icon-cloud-upload"></span> Release</button>
                <button type="button" id="reloadPage" style="display: none;" onclick="window.location.reload()" class="am-btn am-btn-xs am-btn-warning am-round"><span class="am-icon-retweet"></span> Reload</button>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-6 am-text-right">
            <a href="<?=$_SERVER['REQUEST_SCHEME']?>://<?=$_SERVER['SERVER_NAME']?>/api/ctr?svc=swmgr" target="_blank"
               class="am-badge am-round am-badge-secondary am-text-xs">
                Test API
            </a>
            &nbsp;&nbsp;
            <span class="am-badge am-round am-badge-warning am-text-xs">Total: <strong><?=sizeof($task)?></strong></span>
            &nbsp;&nbsp;
            <span class="am-badge am-round am-badge-danger am-text-xs">Version: <strong><?=date("Y-m-d H:i:s", $vsvc->vcode)?></strong></span>

        </div>

    </div>


    <div class="am-g">
        <div class="am-u-sm-12">

            <div class="am-tabs" data-am-tabs>
                <ul class="am-tabs-nav am-nav am-nav-tabs">
                    <li class="am-active"><a href="#tab_summary">Summary</a></li>
                    <li><a href="#tab_create">Create New</a></li>
                </ul>

                <div class="am-tabs-bd">
                    <?/*Summary*/?>
                    <div class="am-tab-panel am-fade am-in am-active" id="tab_summary">

                        <ul class="am-list am-list-static am-list-border">
                            <? foreach($task as $key => $p): ?>
                                <li>
                                    <?if(!empty($p->downloadUrl)):?>
                                        <span class="am-badge am-badge-primary"><?=$p->downloadUrl?></span>
                                    <?else:?>
                                        <span class="am-badge am-badge-danger">无下载地址</span>
                                    <?endif?>

                                    <?=$p->name?> - <?=$p->versionName?>
                                </li>
                            <?endforeach?>
                        </ul>

                    </div>
                    <?/*Summary end*/?>

                    <?/*Create*/?>
                    <div class="am-tab-panel am-fade" id="tab_create">

                        <form name="frmCreate" id="frmCreate" class="am-form am-form-horizontal">
                            <?foreach($task->getFirst() as $k => $v):?>
                                <?if($k == 'id' || $k=='createTime' || $k=='updateTime' || $k=='signature')continue;?>

                                <div class="am-form-group">
                                    <label for="<?=$k?>" class="am-u-sm-2 am-form-label"><?=ucfirst($k)?></label>
                                    <div class="am-u-sm-8 am-u-end">
                                        <?if($k=='category'):?>
                                            <?=$this->tag->select(array($k,SwmgrCategory::find(),"using" => array("id", "name")))?>
                                        <?elseif($k=='status'):?>
                                            <?=$this->tag->selectStatic(array($k,array("1" => "启用","0" => "禁用")))?>
                                        <?elseif($k=='arch'):?>
                                            <?=$this->tag->selectStatic(array($k,array("32" => "32位 系统架构","64" => "64位 系统架构")))?>
                                        <?elseif($k=='windowsVersion'):?>
                                            <?=$this->tag->selectStatic(array($k,Element::windowsVersion()))?>
                                        <?elseif($k=='incomeShare' || $k=='isAd'):?>
                                            <?=$this->tag->selectStatic(array($k,array("0" => "NO", "1" => "YES")))?>
                                        <?elseif($k=='language'):?>
                                            <?=$this->tag->selectStatic(array($k,array("简体中文","繁体中文","English")))?>
                                        <?elseif($k=='rating'):?>
                                            <?=$this->tag->selectStatic(array($k,range(0,9)))?>
                                        <?elseif($k=='description' || $k=='updateInfo' || $k=='brief'):?>
                                            <?=$this->tag->textArea(array($k,ucfirst($v),"cols" => "6","rows" => 3))?>
                                        <?elseif($k=='versionCode' || $k=='size'):?>
                                            <?=$this->tag->numericField(array($k, 'class'=>'am-form-field', 'placeholder'=>ucfirst($k)))?>
                                        <?elseif($k=='iconUrl' || $k=='largeIcon'):?>
                                            <?=$this->tag->fileField(array($k, 'class'=>'am-form-field', 'placeholder'=>ucfirst($k)))?>
                                        <?elseif($k=='screenshotsUrl'):?>
                                            <?=$this->tag->fileField(array($k, 'class'=>'am-form-field','multiple'=>'multiple','placeholder'=>ucfirst($k)))?>
                                        <?else:?>
                                            <?=$this->tag->textField(array($k, 'class'=>'am-form-field', 'placeholder'=>ucfirst($k)))?>
                                        <?endif?>
                                    </div>
                                </div>

                            <?endforeach?>
                            <div class="am-form-group">
                                <div class="am-u-sm-offset-2 am-u-sm-8 am-u-end">
                                    <button type="submit" class="am-btn am-btn-primary am-btn-block">CREATE</button>
                                </div>
                            </div>

                        </form>

                    </div>
                    <?/*Create*/?>
                </div>
            </div>

        </div>

    </div>
</div>
<!-- content end -->


<script>
    $(function(){
        /**
         * Release task
         */
        $("#release").click(function(){
            /*
             layer.confirm('Are you sure?', {icon: 3}, function(index){
             layer.close(index);
             $("#release span").removeClass("am-icon-cloud-upload").addClass("am-icon-spinner am-icon-pulse");

             $.ajax({
             url: '<?=$_SERVER['REQUEST_URI']?>',
             type: 'PUT',
             //async:false,
             cache:false,
             success: function(response) {
             $("#release span").removeClass("am-icon-spinner am-icon-pulse").addClass("am-icon-cloud-upload");
             if(response.code == 0) {
             $("#release").attr("disabled", true).hide();
             $("#reloadPage").show();
             layer.msg(response.msg);
             layer.tips('Upload Successfully, Please Refresh This Page!', '#reloadPage',{tips: [1, '#f37b1d'],time: 400000});
             }else{
             layer.alert(response.msg, {icon: 11});
             }
             }
             }, 'JSON');
             });
             */
        });//end


        <?/*上传包验证*/?>
        $("#frmCreate").validity(function() {
            event.preventDefault();
            $("#packageName").require().match("string");
            $("#arch").require().match("number");
            $("#windowsVersion").require().match("number");
            $("#name").require().match("string");
            $("#category").require().match("number");
            $("#description").require().match("string");
            $("#developer").require().match("string");
            $("#iconUrl").require();
            $("#largeIcon").require();
            $("#screenshotsUrl").require();
            $("#downloadUrl").require().match("string");
            $("#incomeShare").require().match("number");
            $("#rating").require().match("number");
            $("#versionName").require().match("string");
            $("#versionCode").require().match("string");
            $("#priceInfo").require().match("string");
            $("#tag").require().match("string");
            $("#hash").require().match("string");
            $("#size").require().match("number");
            //$("#createTime").require().match("datetime");
            //$("#updateTime").require().match("datetime");
            //$("#signature").require().match("string").lessThanOrEqualTo(32);
            $("#updateInfo").require().match("string");
            $("#language").require().match("number");
            $("#brief").require().match("string");
            $("#isAd").require().match("number");
            $("#status").require().match("number");
            $(this).submit();
        });

    });

</script>
