<header class="am-topbar admin-header am-topbar-inverse">
    <div class="am-topbar-brand">
        <strong>DATACLD</strong>
        <small>CONTROL CENTER</small>
    </div>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only" data-am-collapse="{target: '#topbar-collapse'}">
        <span class="am-sr-only">Switch Navigation</span> <span class="am-icon-bars"></span>
    </button>

    <div class="am-collapse am-topbar-collapse" id="topbar-collapse">

        <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
            <li>
                <a href="javascript:;"><span class="am-icon-envelope-o"></span> Messages <span class="am-badge am-badge-warning">1</span></a>
            </li>

            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    <span class="am-icon-user"></span> Administrator <span class="am-icon-caret-down"></span>
                </a>
                <ul class="am-dropdown-content">
                    <li><a href="/cp/profile"><span class="am-icon-file-text"></span> Profile</a></li>
                    <li><a href="/cp/option"><span class="am-icon-cog"></span> Option</a></li>
                    <li><a href="/cp/logout"><span class="am-icon-power-off"></span> Exit</a></li>
                </ul>
            </li>

            <li class="am-hide-sm-only"><a href="javascript:;" id="admin-fullscreen">
                <span class="am-icon-arrows-alt"></span> <span class="admin-fullText">Full Screen</span></a>
            </li>

        </ul>
    </div>

</header>
