<? $title = "Pre Installed Software Service Management" ?>


<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small>Pre Installed Software Service Management</small>
        </div>
    </div>

    <div class="am-g am-margin-bottom-xs">

        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs  am-align-right">
                    <button type="button" class="am-btn am-btn-secondary am-round"><span class="am-icon-plus"></span> New</button>
                    <button type="button" class="am-btn am-btn-primary"><span class="am-icon-save"></span> Save</button>
                    <button type="button" class="am-btn am-btn-danger am-round"><span class="am-icon-trash-o"></span> Remove</button>
                </div>
                <button type="button" class="am-btn am-btn-xs am-btn-success am-round"><span class="am-icon-play"></span> Release</button>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-6 am-text-right">
            <span class="am-badge am-round am-badge-warning am-text-xs">
                Total: <strong><?=sizeof($list->files)?></strong>
            </span>
            &nbsp;&nbsp;
            <span class="am-badge am-round am-badge-danger am-text-xs">
                Version: <strong><?=$list->version?></strong>
            </span>
        </div>


    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form">
                <table
                    class="am-table  am-table-bordered am-table-radius am-table-compact am-table-striped am-table-hover table-main">
                    <thead>
                    <tr>
                        <th class="table-check am-text-center"><input type="checkbox" onclick="SelectAll()"/></th>
                        <th class="table-id am-text-center">ID</th>
                        <? foreach($list->files[0] as $key => $p): ?>
                            <th class="am-text-center">
                                <?=ucfirst($key)?>
                            </th>
                        <? endforeach ?>
                        <th class="table-set am-text-center">Operation</th>
                    </tr>
                    </thead>
                    <tbody>
                    <? foreach($list->files as $key => $p): ?>
                        <tr>
                            <td class="am-text-center"><input type="checkbox" name="record" value="<?=$key?>"/></td>
                            <td class="am-text-center"><?=$key?></td>
                            <? foreach($p as $key => $v): ?>
                                <td class="am-text-center">
                                    <? if(strstr(strtolower($key), 'size')): ?>
                                        <?=DYP\Sys\Command::fmtDataSize($v)?>
                                    <? elseif(strstr(strtolower($key), 'downloadurl')): ?>
                                        <a href="<?=$v?>" target="_blank"
                                           class="am-btn am-btn-xs am-btn-secondary">Download</a>
                                    <? else: ?>
                                        <?=$v?>
                                    <? endif ?>
                                </td>
                            <? endforeach ?>
                            <td class="am-text-center">
                                <div class="am-btn-toolbar am-text-center">
                                    <div class="am-btn-group am-btn-group-xs">
                                        <button class="am-btn am-btn-primary am-radius"><span class="am-icon-pencil"></span></button>
                                        <button class="am-btn am-btn-danger am-radius"><span class="am-icon-remove"></span></button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <? endforeach ?>
                    </tbody>
                </table>

            </form>
        </div>

    </div>
</div>
<!-- content end -->

<script>
    checkit = true;
    function SelectAll() {
        el = document.getElementsByName("record");
        if (checkit) {
            for (i = 0; i < el.length; i++)
                el.item(i).checked = true;
            checkit = false;
        }
        else {
            for (i = 0; i < el.length; i++)
                el.item(i).checked = false;
            checkit = true;
        }
    }
</script>

