<? $title = "Pre Installed Software Service Management" ?>


<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small>Pre Installed Software Service Management</small>
        </div>
    </div>

    <div class="am-g am-margin-bottom-xs">
        <div class="am-u-sm-12 am-u-md-6">
            <div class="am-btn-toolbar">
                <div class="am-btn-group am-btn-group-xs">
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-plus"></span> New</button>
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-save"></span> Save</button>
                    <button type="button" class="am-btn am-btn-default"><span class="am-icon-trash-o"></span> Remove
                    </button>
                </div>
            </div>
        </div>

        <div class="am-u-sm-12 am-u-md-6 am-text-right">
            <span class="am-badge am-round am-badge-danger am-text-sm">
                Version: <strong><?=$list->version?></strong>
            </span>
            &nbsp;&nbsp;
            <span class="am-badge am-round am-badge-warning am-text-sm">
                Total: <strong><?=sizeof($list->files)?></strong>
            </span>
        </div>

    </div>

    <div class="am-g">
        <div class="am-u-sm-12">
            <form class="am-form">
                <table
                    class="am-table  am-table-bordered am-table-radius am-table-compact am-table-striped am-table-hover table-main">
                    <thead>
                    <tr>
                        <th class="table-check am-text-center"><input type="checkbox" onclick="SelectAll()"/></th>
                        <th class="table-id am-text-center">ID</th>
                        <th class="table-title am-text-center">Name</th>
                        <th class="table-type am-text-center">package</th>
                        <th class="table-date am-text-center am-hide-sm-only">File Size</th>
                        <th class="table-date am-text-center am-hide-sm-only">Hash</th>
                        <th class="table-date am-text-center am-hide-sm-only">Release Time</th>
                        <th class="table-date am-text-center am-hide-sm-only">Download Url</th>
                        <th class="table-set">Operation</th>
                    </tr>
                    </thead>
                    <tbody>

                    <? foreach($list->files as $key => $p): ?>
                        <tr>
                            <td class="am-text-center"><input type="checkbox" name="record" value="<?=$key?>"/></td>
                            <td class="am-text-center"><?=$key?></td>
                            <td class="am-text-center"><a href="javascript:void(0);"><?=$p->name?></a></td>
                            <td class="am-text-center"><a href="javascript:void(0);"><?=$p->package?></a></td>
                            <td class="am-text-center"><?=sizeFmt($p->fileSize)?></td>
                            <td class="am-text-center"><?=$p->hash?></td>
                            <td class="am-text-center am-hide-sm-only"><?=$p->releaseTime?></td>
                            <td class="am-text-center am-hide-sm-only"><a href="<?=$p->fetchUrl?>" target="_blank">Download</a>
                            </td>
                            <td class="am-text-center">
                                <div class="am-btn-toolbar">
                                    <div class="am-btn-group am-btn-group-xs">
                                        <button class="am-btn am-btn-default am-btn-xs am-text-secondary"><span
                                                class="am-icon-pencil-square-o"></span> Edit
                                        </button>
                                        <button
                                            class="am-btn am-btn-default am-btn-xs am-text-danger am-hide-sm-only"><span
                                                class="am-icon-trash-o"></span> Remove
                                        </button>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <? endforeach ?>

                    </tbody>
                </table>
            </form>
        </div>

    </div>
</div>
<!-- content end -->

<script>
    checkit = true;
    function SelectAll() {
        el = document.getElementsByName("record");
        if (checkit) {
            for (i = 0; i < el.length; i++)
                el.item(i).checked = true;
            checkit = false;
        }
        else {
            for (i = 0; i < el.length; i++)
                el.item(i).checked = false;
            checkit = true;
        }
    }
</script>
