<?use DYP\Tags\Element;?>
<?$title = "Software Manager Service / Category Management" ?>
<?=$this->tag->javascriptInclude("assets/js/layer/layer.js");?>

<?//=$this->tag->stylesheetLink("assets/js/editable-table/index.css");?>
<?=$this->tag->javascriptInclude("assets/js/tabledit/jquery.tabledit.js");?>


<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small><?=$title?></small>
        </div>
    </div>

    <div class="am-g">
        <div class="am-u-sm-12">

            <div class="am-tabs" data-am-tabs>
                <ul class="am-tabs-nav am-nav am-nav-tabs">
                    <li class="am-active"><a href="#tab_summary">Summary</a></li>
                    <li><a href="#tab_create">Create New</a></li>
                </ul>

                <div class="am-tabs-bd">

                    <?/*Summary*/?>
                    <div class="am-tab-panel am-fade am-in am-active" id="tab_summary">

                        <table id="SummaryTable" class="am-table am-table-bordered am-table-radius am-table-compact am-table-striped am-table-hover table-main">
                            <thead>
                            <tr>
                                <? foreach($task->getFirst() as $k => $v): ?>

                                    <th class="am-text-center">
                                        <?if(strtolower($k) == 'status'):?>
                                            STATUS
                                        <?else:?>
                                            <?=strtoupper($k)?>
                                        <?endif?>
                                    </th>
                                <? endforeach ?>
                            </tr>
                            </thead>
                            <tbody>
                            <? foreach($task as $key => $p): ?>
                                <tr id="<?=$p->id?>" <?if($p->status != 1):?>class="am-disabled"<?endif?>>
                                    <? foreach($p as $key => $v): ?>
                                        <td class="am-text-center">
                                        <?if(strtolower($key) == 'status'):?>
                                            <?=Element::getStatusText($v)?>
                                        <?else:?>
                                            <?=strtoupper($v)?>
                                        <?endif?>
                                        </td>
                                    <? endforeach ?>
                                </tr>
                            <? endforeach ?>
                            </tbody>
                        </table>

                    </div>
                    <?/*Summary end*/?>


                    <?/*Create*/?>
                    <div class="am-tab-panel am-fade" id="tab_create">

                        <form id="frmCreate" class="am-form am-form-horizontal">

                            <?foreach($task->getFirst() as $k => $v):?><?if(strtolower($k) == 'id' || strtolower($k) == 'total'){continue;}?>

                            <div class="am-form-group">
                                <label for="<?=$k?>" class="am-u-sm-2 am-form-label"><?=strtoupper($k)?></label>
                                <div class="am-u-sm-10">
                                    <?if(strtolower($k) == 'status'):?>
                                    <?=Element::frmStatus($v, '',$k,$k);?>
                                    <?else:?>
                                    <input type="text" name="<?=$k?>" id="<?=$k?>" placeholder="<?=ucfirst($k)?>">
                                    <?endif?>
                                </div>
                            </div>
                            <?endforeach?>

                            <div class="am-form-group">
                                <div class="am-u-sm-10 am-u-sm-offset-2">
                                    <button type="submit" id="create" class="am-btn am-btn-default">CREATE</button>
                                </div>
                            </div>
                        </form>

                    </div>
                    <?/*Create*/?>

                </div>
            </div>

        </div>

    </div>
</div>
<!-- content end -->


<script>
$(function(){

    $('#SummaryTable').Tabledit({
        url: '<?=$_SERVER['REQUEST_URI']?>',
        eventType: 'dblclick',
        editButton:true,
        deleteButton:false,
        restoreButton:false,
        buttons: {edit: {action: 'edit'}},
        columns: {
            identifier: [0, 'id'],
            editable: [[1, 'name'],[2, 'alias'],[3, 'total'], [4, 'status', '{"1":"ENABLE", "0":"DISABLE","3":"DELETE"}']]
        },
        onDraw: function() {
            //console.log('onDraw()');
        },
        onSuccess: function(data, textStatus, jqXHR) {
            console.log($(this).parent());
            layer.closeAll('loading');
            if (data.code == 0) {
                layer.msg(data.msg,{icon: 6});
            } else {
                layer.alert(data.msg, {icon: 11});
            }
        },
        onFail: function(jqXHR, textStatus, errorThrown) {
            layer.closeAll('loading');
            layer.msg('PROGRESSING FAILURE!',{icon: 11});
        },
        onAlways: function() {
            //console.log('onAlways()');
            return false;
        },
        onAjax: function(action, serialize) {
            layer.load();
        }
    });

    /**
     * Create
     */
    $('#create').bind('click', function(){
        event.preventDefault();
        $.ajax({url: '<?=$_SERVER['REQUEST_URI']?>',
            type: 'POST',
            data: $('#frmCreate').serialize(),
            cache: false,
            success: function (respond) {
                if (respond.code == 0) {
                    layer.msg(respond.msg);
                    window.location.reload();
                } else {
                    layer.alert(respond.msg, {icon: 11});
                }
            }
        }, 'JSON');
    });//create

});
</script>
