<?$title = "Software Manager Service / Package Management" ?>
<?=$this->tag->javascriptInclude("assets/js/layer/layer.js");?>
<?=$this->tag->javascriptInclude("assets/js/handsontable/dist/handsontable.full.min.js");?>
<?=$this->tag->stylesheetLink("assets/js/handsontable/dist/handsontable.full.min.css");?>

<?
$ft = [];
foreach($task->getFirst() as $k => $v){
    $ft[] = $k;
}
$fd=[];
$taskAr = $task->toArray();

$fkey = false;
$fdat = [];
foreach($taskAr as $k => $v){
    if($fkey === false) $fkey = array_keys($v);
    $fdat[] = array_values($v);
}
//dd($fields);
//$fields_data = json_encode($fields);
?>

<!-- content start -->
<div class="admin-content">

    <div class="am-cf am-padding">
        <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">Home</strong> /
            <small><?=$title?></small>
        </div>
    </div>

    <div class="am-g am-margin-bottom-xs">

        <div class="am-u-sm-12 am-text-right">
            <span class="am-badge am-badge-primary">Total: <strong><?=sizeof($task)?></strong></span>
            <span class="am-badge am-badge-secondary">Version: <strong><?=date("Y-m-d H:i:s", $vsvc->vcode)?></strong></span>
            <a href="javascript:void(0);" id="release" class="am-badge am-badge-success am-round"><span class="am-icon-cloud-upload"></span> Release</a>
        </div>

    </div>


    <div class="am-g">
        <div class="am-u-sm-12">
            <div id="dataland"></div>
            <script>
                var ftitle=<?=json_encode($fkey)?>;
                var fdata = [];
                //var data = [['Column A', 'Column B', 'Column C'], ['1', '2', '3']];
                var data = [ftitle, <?foreach($fdat as $v):?><?=json_encode($v)?>,<?endforeach?>];
                var container = document.getElementById("dataland");
                var hot = new Handsontable(container, {
                    data: data
                });
            </script>
        </div>
    </div>


    <div class="am-g">
        <div class="am-u-sm-12">

            <div class="am-tabs" data-am-tabs>
                <ul class="am-tabs-nav am-nav am-nav-tabs">
                    <li class="am-active"><a href="#tab_summary">Summary</a></li>
                    <li><a href="#tab_create">Create New</a></li>
                </ul>

                <div class="am-tabs-bd">
                    <?/*Summary*/?>
                    <div class="am-tab-panel am-fade am-in am-active" id="tab_summary">

                        <ul class="am-list am-list-static am-list-border">
                        <? foreach($task as $key => $p): ?>
                            <li>
                                <?if(!empty($p->downloadUrl)):?>
                                    <span class="am-badge am-badge-primary"><?=$p->downloadUrl?></span>
                                <?else:?>
                                    <span class="am-badge am-badge-danger">无下载地址</span>
                                <?endif?>

                                <?=$p->name?> - <?=$p->versionName?>
                            </li>
                        <?endforeach?>
                        </ul>

                    </div>
                    <?/*Summary end*/?>

                    <?/*Create*/?>
                    <div class="am-tab-panel am-fade" id="tab_create">

                        <form class="am-form">
                            <fieldset class="am-form-set">
                                <?foreach($task->getFirst() as $k => $v):?>

                                    <?if(strtolower($k) == 'id' || strtolower($k) == 'total' || strtolower($k) == 'status'){continue;}?>

                                    <div class="am-input-group am-input-group-sm am-margin-top-xs">
                                        <span class="am-input-group-label am-text-right"><?=ucfirst($k)?></span>
                                        <input type="text" class="am-form-field" placeholder="<?=ucfirst($k)?>">
                                    </div>

                                <?endforeach?>

                            </fieldset>
                            <button type="submit" class="am-btn am-btn-primary am-btn-block">CREATE</button>
                        </form>

                    </div>
                    <?/*Create*/?>
                </div>
            </div>

        </div>

    </div>
</div>
<!-- content end -->


<script>
    checkit = true;
    function SelectAll() {
        el = document.getElementsByName("record");
        if (checkit) {
            for (i = 0; i < el.length; i++)
                el.item(i).checked = true;
            checkit = false;
        }
        else {
            for (i = 0; i < el.length; i++)
                el.item(i).checked = false;
            checkit = true;
        }
    }

    $(function(){
        /**
         * Release task
         */
        $("#release").click(function(){
            layer.confirm('Are you sure?', {icon: 3}, function(index){
                layer.close(index);
                $("#release span").removeClass("am-icon-cloud-upload").addClass("am-icon-spinner am-icon-pulse");

                $.ajax({
                    url: '<?=$_SERVER['REQUEST_URI']?>',
                    type: 'PUT',
                    //async:false,
                    cache:false,
                    success: function(response) {
                        $("#release span").removeClass("am-icon-spinner am-icon-pulse").addClass("am-icon-cloud-upload");
                        if(response.code == 0) {
                            $("#release").attr("disabled", true).hide();
                            $("#reloadPage").show();
                            layer.msg(response.msg);
                            layer.tips('Upload Successfully, Please Refresh This Page!', '#reloadPage',{tips: [1, '#f37b1d'],time: 400000});
                        }else{
                            layer.alert(response.msg, {icon: 11});
                        }
                    }
                }, 'JSON');
            });

        });//end

    });

</script>
