<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title><?=(isset($title))?$title:""?> | DataCloud</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>

    <link rel="alternate icon" type="image/png" href="/assets/am/i/favicon.png">
    <link rel="stylesheet" href="/assets/am/css/amazeui.min.css"/>
    <link rel="stylesheet" href="/assets/am/css/amazeui.flat.min.css"/>
    <link rel="stylesheet" href="/assets/am/css/admin.css"/>


    <!--[if lt IE 9]>
    <script src="http://libs.baidu.com/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
    <script src="/assets/am/js/polyfill/rem.min.js"></script>
    <script src="/assets/am/js/polyfill/respond.min.js"></script>
    <script src="/assets/am/js/amazeui.legacy.js"></script>
    <![endif]-->

    <!--[if (gte IE 9)|!(IE)]><!-->
    <script src="/assets/am/js/jquery.min.js"></script>
    <script src="/assets/am/js/amazeui.min.js"></script>
    <!--<![endif]-->

    <script src="/assets/am/js/app.js"></script>

</head>
<body>
<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，DATACLD 服务暂不支持。
    请 <a href="http://browsehappy.com/" target="_blank">升级浏览器</a>以获得更好的体验！</p>
<![endif]-->

<?$this->partial("cp/_top_nav", array("active"=>'index'))?>

<div class="am-cf admin-main">
    <?$this->partial("cp/_sidebar", array("active"=>'index'))?>
    <?= $this->getContent() ?>
</div>

<?$this->partial("cp/_footer")?>

</body>
</html>
